<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Hermes.ApiClient\Hermes.ApiClient.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Hermes.TrayApp</RootNamespace>
    <AssemblyName>HermesTray</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System.Drawing" />
    <Using Include="System.Reflection" />
    <Using Include="System.Windows.Forms" />
  </ItemGroup>

</Project>